version: "3.9"

services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: textbook
      TZ: UTC
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      # Runs only on first init of a brand-new volume
      - ./backend/initdb:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d textbook"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped

  # Applies schema every time (safe, idempotent).
  migrate:
    image: pgvector/pgvector:pg16
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGPASSWORD: postgres
    command: >
      bash -lc '
      until pg_isready -h db -U postgres -d textbook; do sleep 1; done;
      psql -h db -U postgres -d textbook -v ON_ERROR_STOP=1 -f /migrations/001_init.sql
      '
    volumes:
      - ./backend/migrations:/migrations:ro
    restart: "no"

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://postgres:postgres@db:5432/textbook}
      EMBEDDING_MODEL: ${EMBEDDING_MODEL:-sentence-transformers/all-MiniLM-L6-v2}
      EMBEDDING_DIM: ${EMBEDDING_DIM:-384}
      IVFFLAT_PROBES: ${IVFFLAT_PROBES:-10}
      TZ: UTC
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: sh -c "rm -rf /webroot/* && cp -r /app/dist/* /webroot/"
    environment:
      NODE_ENV: production
    volumes:
      - webroot:/webroot
    depends_on:
      - api
    restart: "no"

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - api
      - frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - webroot:/usr/share/nginx/html:ro
    restart: unless-stopped

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  pgdata:
  webroot:
